In [18]:
import pandas as pd
import os

# Cargar el archivo Excel con los datos
ruta_archivo = r"C:\Users\HP\Desktop\Informe de saldos por departamento.xlsx"  # Cambia por la ruta de tu archivo
df = pd.read_excel(ruta_archivo, sheet_name="INFORME BANCARIO")

# Lista completa de departamentos que debe estar en el resultado
departamentos = ['T1', 'T2', 'T3', 'T4', 'T5', '1A', '1B', '1C', '1D', '1E', '2A', '2B', '2C', '2D', '2E',
                 '3A', '3B', '3C', '3D', '3E', '4A', '4B', '4C', '4D', '4E', '5A', '5B', '5C', '5D', '5E',
                 '6A', '6B', '6C', '6D', '6E', '7A', '7B', '7C', '7D', '7E', '8A', '8B', '8C', '8D', '8E',
                 '9A', '9B', '9C', '9D', '9E']

# Crear un DataFrame con los departamentos
df_departamentos = pd.DataFrame(departamentos, columns=['DEPARTAMENTO/TIENDA'])

# Filtrar los depósitos (considerando que los montos negativos son retiros, así que solo nos interesan los positivos)
df_depositos = df[df['Monto'] > 0]

# Agrupar los montos por departamento y calcular el total por cada uno
depositos_por_departamento = df_depositos.groupby('DEPARTAMENTO/TIENDA')['Monto'].sum().reset_index()

# Hacer un merge con la lista completa de departamentos para asegurar que todos aparezcan, incluso los que no tienen depósitos
resultado_final = pd.merge(df_departamentos, depositos_por_departamento, on='DEPARTAMENTO/TIENDA', how='left')

# Rellenar los NaN (es decir, los departamentos sin depósitos) con 0
resultado_final['Monto'].fillna(0, inplace=True)

# Mostrar el resultado
print(resultado_final)

# Guardar el resultado en un archivo Excel en la misma carpeta que el archivo original
directorio_archivo = os.path.dirname(ruta_archivo)
nombre_salida = os.path.join(directorio_archivo, 'depositos_por_departamento_completo.xlsx')
resultado_final.to_excel(nombre_salida, index=False)

print(f"Archivo guardado en: {nombre_salida}")

   DEPARTAMENTO/TIENDA    Monto
0                   T1  2566.05
1                   T2   350.00
2                   T3    79.08
3                   T4  1539.21
4                   T5  1577.69
5                   1A  2320.85
6                   1B     0.00
7                   1C  2595.93
8                   1D  1289.00
9                   1E  1404.00
10                  2A  1396.95
11                  2B  1744.99
12                  2C  1670.09
13                  2D   751.90
14                  2E  1437.09
15                  3A   696.00
16                  3B  1023.93
17                  3C  2002.30
18                  3D  1200.00
19                  3E  1965.72
20                  4A  1666.80
21                  4B     0.00
22                  4C  2088.41
23                  4D   572.41
24                  4E     0.00
25                  5A  1713.53
26                  5B  1393.33
27                  5C  1208.79
28                  5D   753.62
29                  5E  1872.20
30                  6A  1728.60
31                  6B     0.00
32                  6C  1855.88
33                  6D   566.73
34                  6E  1638.21
35                  7A  1925.00
36                  7B  1706.53
37                  7C  1666.09
38                  7D   560.17
39                  7E  2045.80
40                  8A  1796.95
41                  8B  1753.48
42                  8C  2094.00
43                  8D   673.50
44                  8E  2485.00
45                  9A  1830.32
46                  9B  1590.00
47                  9C  1932.87
48                  9D   737.37
49                  9E  2885.68
Archivo guardado en: C:\Users\HP\Desktop\depositos_por_departamento_completo.xlsx

C:\Users\HP\AppData\Local\Temp\ipykernel_25496\2322012327.py:27: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  resultado_final['Monto'].fillna(0, inplace=True)